2025-04-14 13:43:49,969 - cephci - log:161 - DEBUG - Completed log configuration
2025-04-14 13:43:49,972 - cephci - run:722 - INFO - Running test cephfs_nfs.nfs_snaphshot_clone.py
2025-04-14 13:43:49,972 - cephci - nfs_snaphshot_clone:40 - INFO - Running cephfs CEPH-83574024 test case
2025-04-14 13:43:49,974 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.251
2025-04-14 13:43:50,978 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 13:43:52,571 - cephci - ceph:1186 - DEBUG - 
2025-04-14 13:43:52,571 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 13:43:52,571 - cephci - ceph:1186 - DEBUG - 
2025-04-14 13:43:53,454 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 0:07:59 ago on Mon Apr 14 13:35:33 2025.
2025-04-14 13:43:53,689 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 13:43:53,690 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 13:43:53,691 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 13:43:53,693 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 13:43:53,694 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 13:43:53,695 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 13:43:53,696 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 13:43:53,697 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 13:43:53,698 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 13:43:53,700 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 13:43:53,796 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 13:43:53,797 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 13:43:53,797 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 13:43:53,931 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.251 took 3.95635 seconds
2025-04-14 13:43:53,972 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.251
2025-04-14 13:43:54,976 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 13:43:54,977 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 13:43:54,977 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 13:43:54,977 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 13:43:54,977 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 13:43:54,977 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 13:43:54,978 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.251 took 1.004847 seconds
2025-04-14 13:43:54,979 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.251
2025-04-14 13:43:55,983 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.251 took 1.00372 seconds
2025-04-14 13:43:55,985 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.251
2025-04-14 13:43:56,989 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.251 took 1.003852 seconds
2025-04-14 13:43:56,998 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.3
2025-04-14 13:43:58,002 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 13:43:58,652 - cephci - ceph:1186 - DEBUG - 
2025-04-14 13:43:58,652 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 13:43:58,652 - cephci - ceph:1186 - DEBUG - 
2025-04-14 13:43:59,565 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 0:06:29 ago on Mon Apr 14 13:37:09 2025.
2025-04-14 13:43:59,839 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 13:43:59,840 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 13:43:59,842 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 13:43:59,843 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 13:43:59,844 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 13:43:59,845 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 13:43:59,847 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 13:43:59,848 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 13:43:59,849 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 13:43:59,851 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 13:43:59,946 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 13:43:59,947 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 13:43:59,947 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 13:44:00,057 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.3 took 3.059104 seconds
2025-04-14 13:44:00,099 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.3
2025-04-14 13:44:01,103 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 13:44:01,104 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 13:44:01,104 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 13:44:01,104 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 13:44:01,104 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 13:44:01,104 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 13:44:01,105 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.3 took 1.004995 seconds
2025-04-14 13:44:01,106 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.3
2025-04-14 13:44:02,111 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.3 took 1.00382 seconds
2025-04-14 13:44:02,112 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.3
2025-04-14 13:44:03,116 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.3 took 1.00343 seconds
2025-04-14 13:44:03,119 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.202
2025-04-14 13:44:04,123 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 13:44:05,660 - cephci - ceph:1186 - DEBUG - 
2025-04-14 13:44:05,660 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 13:44:05,660 - cephci - ceph:1186 - DEBUG - 
2025-04-14 13:44:06,410 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 0:04:27 ago on Mon Apr 14 13:39:18 2025.
2025-04-14 13:44:06,640 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 13:44:06,641 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 13:44:06,643 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 13:44:06,644 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 13:44:06,645 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 13:44:06,646 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 13:44:06,647 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 13:44:06,649 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 13:44:06,650 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 13:44:06,651 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 13:44:06,745 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 13:44:06,746 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 13:44:06,746 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 13:44:07,912 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.202 took 4.793017 seconds
2025-04-14 13:44:07,914 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.202
2025-04-14 13:44:08,918 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 13:44:08,918 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 13:44:08,919 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 13:44:08,919 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 13:44:08,919 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 13:44:08,919 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 13:44:08,919 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.202 took 1.004694 seconds
2025-04-14 13:44:08,921 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.202
2025-04-14 13:44:09,924 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.202 took 1.003538 seconds
2025-04-14 13:44:09,926 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.202
2025-04-14 13:44:10,930 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.202 took 1.003682 seconds
2025-04-14 13:44:10,932 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.142
2025-04-14 13:44:11,936 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 13:44:12,504 - cephci - ceph:1186 - DEBUG - 
2025-04-14 13:44:12,504 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 13:44:12,504 - cephci - ceph:1186 - DEBUG - 
2025-04-14 13:44:13,355 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 0:01:47 ago on Mon Apr 14 13:42:05 2025.
2025-04-14 13:44:13,607 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 13:44:13,608 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 13:44:13,609 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 13:44:13,611 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 13:44:13,612 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 13:44:13,613 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 13:44:13,614 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 13:44:13,615 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 13:44:13,616 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 13:44:13,617 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 13:44:13,709 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 13:44:13,710 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 13:44:13,710 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 13:44:13,944 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.142 took 3.011348 seconds
2025-04-14 13:44:13,985 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.142
2025-04-14 13:44:14,989 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 13:44:14,990 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 13:44:14,990 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 13:44:14,990 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 13:44:14,990 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 13:44:14,990 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 13:44:14,991 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.142 took 1.005177 seconds
2025-04-14 13:44:14,992 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.142
2025-04-14 13:44:15,996 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.142 took 1.003513 seconds
2025-04-14 13:44:15,997 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.142
2025-04-14 13:44:17,001 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.142 took 1.003421 seconds
2025-04-14 13:44:17,003 - cephci - ceph:1576 - INFO - Execute ceph fs ls --format json-pretty on 10.0.195.251
2025-04-14 13:44:18,006 - cephci - ceph:1606 - INFO - Execution of ceph fs ls --format json-pretty on 10.0.195.251 took 1.003235 seconds
2025-04-14 13:44:18,007 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 13:44:18,008 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251
2025-04-14 13:44:19,012 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251 took 1.003142 seconds
2025-04-14 13:44:19,014 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251
2025-04-14 13:44:20,018 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251 took 1.003446 seconds
2025-04-14 13:44:20,020 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node8 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251
2025-04-14 13:44:21,024 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node8 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251 took 1.003447 seconds
2025-04-14 13:44:21,026 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251
2025-04-14 13:44:22,030 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251 took 1.003482 seconds
2025-04-14 13:44:22,031 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 13:44:22,032 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3
2025-04-14 13:44:23,036 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3 took 1.003158 seconds
2025-04-14 13:44:23,037 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3
2025-04-14 13:44:24,040 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3 took 1.002897 seconds
2025-04-14 13:44:24,042 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node9 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3
2025-04-14 13:44:25,046 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node9 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3 took 1.003459 seconds
2025-04-14 13:44:25,048 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3
2025-04-14 13:44:26,052 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3 took 1.003226 seconds
2025-04-14 13:44:26,053 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 13:44:26,055 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202
2025-04-14 13:44:27,059 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202 took 1.004357 seconds
2025-04-14 13:44:27,061 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202
2025-04-14 13:44:28,066 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202 took 1.004202 seconds
2025-04-14 13:44:28,068 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node10 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202
2025-04-14 13:44:29,072 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node10 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202 took 1.003722 seconds
2025-04-14 13:44:29,075 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202
2025-04-14 13:44:30,079 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202 took 1.004119 seconds
2025-04-14 13:44:30,080 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 13:44:30,082 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142
2025-04-14 13:44:31,086 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142 took 1.003625 seconds
2025-04-14 13:44:31,088 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142
2025-04-14 13:44:32,092 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142 took 1.003327 seconds
2025-04-14 13:44:32,093 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node11 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142
2025-04-14 13:44:33,097 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node11 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142 took 1.003342 seconds
2025-04-14 13:44:33,100 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142
2025-04-14 13:44:34,104 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142 took 1.003741 seconds
2025-04-14 13:44:34,108 - cephci - ceph:1576 - INFO - Execute ceph fs ls --format json-pretty on 10.0.195.251
2025-04-14 13:44:35,112 - cephci - ceph:1606 - INFO - Execution of ceph fs ls --format json-pretty on 10.0.195.251 took 1.003976 seconds
2025-04-14 13:44:35,115 - cephci - ceph:1576 - INFO - Execute ceph nfs export create cephfs cephfs-nfs /export_474 cephfs path=/ on 10.0.195.251
2025-04-14 13:44:37,120 - cephci - ceph:1606 - INFO - Execution of ceph nfs export create cephfs cephfs-nfs /export_474 cephfs path=/ on 10.0.195.251 took 2.005055 seconds
2025-04-14 13:44:37,122 - cephci - ceph:1576 - INFO - Execute ceph fs subvolumegroup create cephfs subvolume_group1 on 10.0.195.251
2025-04-14 13:44:39,127 - cephci - ceph:1606 - INFO - Execution of ceph fs subvolumegroup create cephfs subvolume_group1 on 10.0.195.251 took 2.005092 seconds
2025-04-14 13:44:39,129 - cephci - ceph:1576 - INFO - Execute ceph fs subvolumegroup ls cephfs --format json on 10.0.195.251
2025-04-14 13:44:40,133 - cephci - ceph:1606 - INFO - Execution of ceph fs subvolumegroup ls cephfs --format json on 10.0.195.251 took 1.003427 seconds
2025-04-14 13:44:40,136 - cephci - ceph:1576 - INFO - Execute ceph fs subvolume create cephfs subvolume1 --group_name subvolume_group1 on 10.0.195.251
2025-04-14 13:44:41,140 - cephci - ceph:1606 - INFO - Execution of ceph fs subvolume create cephfs subvolume1 --group_name subvolume_group1 on 10.0.195.251 took 1.003723 seconds
2025-04-14 13:44:41,142 - cephci - ceph:1576 - INFO - Execute ceph fs subvolume ls cephfs --group_name subvolume_group1 --format json on 10.0.195.251
2025-04-14 13:44:42,147 - cephci - ceph:1606 - INFO - Execution of ceph fs subvolume ls cephfs --group_name subvolume_group1 --format json on 10.0.195.251 took 1.003805 seconds
2025-04-14 13:44:42,149 - cephci - ceph:1576 - INFO - Execute ceph fs subvolume create cephfs subvolume2 on 10.0.195.251
2025-04-14 13:44:43,153 - cephci - ceph:1606 - INFO - Execution of ceph fs subvolume create cephfs subvolume2 on 10.0.195.251 took 1.003545 seconds
2025-04-14 13:44:43,155 - cephci - ceph:1576 - INFO - Execute ceph fs subvolume ls cephfs --format json on 10.0.195.251
2025-04-14 13:44:44,159 - cephci - ceph:1606 - INFO - Execution of ceph fs subvolume ls cephfs --format json on 10.0.195.251 took 1.003568 seconds
2025-04-14 13:44:44,162 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_Y05CX on 10.0.195.251
2025-04-14 13:44:45,166 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_Y05CX on 10.0.195.251 took 1.003594 seconds
2025-04-14 13:44:45,168 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_474 /mnt/nfs_Y05CX on 10.0.195.251
2025-04-14 13:46:50,916 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_474 /mnt/nfs_Y05CX on 10.0.195.251 took 125.747032 seconds
2025-04-14 13:46:50,917 - cephci - retry:28 - WARNING - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_474 /mnt/nfs_Y05CX returned Created symlink /run/systemd/system/remote-fs.target.wants/rpc-statd.service → /usr/lib/systemd/system/rpc-statd.service.
mount.nfs: Connection refused
 and code 32 on 10.0.195.251, Retrying in 60 seconds...
2025-04-14 13:47:50,965 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_Y05CX on 10.0.195.251
2025-04-14 13:47:51,970 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_Y05CX on 10.0.195.251 took 1.003951 seconds
2025-04-14 13:47:51,972 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_474 /mnt/nfs_Y05CX on 10.0.195.251
2025-04-14 13:49:57,111 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_474 /mnt/nfs_Y05CX on 10.0.195.251 took 125.138366 seconds
2025-04-14 13:49:57,111 - cephci - retry:28 - WARNING - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_474 /mnt/nfs_Y05CX returned mount.nfs: Connection refused
 and code 32 on 10.0.195.251, Retrying in 120 seconds...
2025-04-14 13:51:57,198 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_Y05CX on 10.0.195.251
2025-04-14 13:51:58,202 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_Y05CX on 10.0.195.251 took 1.003414 seconds
2025-04-14 13:51:58,204 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_474 /mnt/nfs_Y05CX on 10.0.195.251
2025-04-14 13:54:03,344 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_474 /mnt/nfs_Y05CX on 10.0.195.251 took 125.138881 seconds
2025-04-14 13:54:03,345 - cephci - nfs_snaphshot_clone:173 - INFO - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_474 /mnt/nfs_Y05CX returned mount.nfs: Connection refused
 and code 32 on 10.0.195.251
2025-04-14 13:54:03,347 - cephci - nfs_snaphshot_clone:174 - INFO - Traceback (most recent call last):
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_nfs/nfs_snaphshot_clone.py", line 104, in run
    rc = fs_util.cephfs_nfs_mount(
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/utility/retry.py", line 32, in f_retry
    return f(*args, **kwargs)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_utilsV1.py", line 3277, in cephfs_nfs_mount
    client.exec_command(sudo=True, cmd=command)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 2305, in exec_command
    return self.node.exec_command(cmd=cmd, **kw)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 1700, in exec_command
    raise CommandFailed(
ceph.ceph.CommandFailed: mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_474 /mnt/nfs_Y05CX returned mount.nfs: Connection refused
 and code 32 on 10.0.195.251

2025-04-14 13:54:03,347 - cephci - nfs_snaphshot_clone:177 - INFO - Cleaning up
2025-04-14 13:54:03,349 - cephci - ceph:1576 - INFO - Execute ceph fs subvolume snapshot rm cephfs subvolume1 snap1 --group_name subvolume_group1 on 10.0.195.251
2025-04-14 13:54:04,352 - cephci - ceph:1606 - INFO - Execution of ceph fs subvolume snapshot rm cephfs subvolume1 snap1 --group_name subvolume_group1 on 10.0.195.251 took 1.003373 seconds
2025-04-14 13:54:04,354 - cephci - ceph:1576 - INFO - Execute ceph fs subvolume snapshot rm cephfs subvolume2 snap2 on 10.0.195.251
2025-04-14 13:54:05,357 - cephci - ceph:1606 - INFO - Execution of ceph fs subvolume snapshot rm cephfs subvolume2 snap2 on 10.0.195.251 took 1.003275 seconds
2025-04-14 13:54:05,359 - cephci - ceph:1576 - INFO - Execute rm -rf /mnt/nfs_Y05CX/* on 10.0.195.251
2025-04-14 13:54:06,363 - cephci - ceph:1606 - INFO - Execution of rm -rf /mnt/nfs_Y05CX/* on 10.0.195.251 took 1.003421 seconds
2025-04-14 13:54:06,364 - cephci - ceph:1576 - INFO - Execute umount /mnt/nfs_Y05CX on 10.0.195.251
2025-04-14 13:54:07,368 - cephci - ceph:1606 - INFO - Execution of umount /mnt/nfs_Y05CX on 10.0.195.251 took 1.003391 seconds
2025-04-14 13:54:07,369 - cephci - run:854 - ERROR - umount /mnt/nfs_Y05CX returned umount: /mnt/nfs_Y05CX: not mounted.
 and code 32 on 10.0.195.251
Traceback (most recent call last):
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/run.py", line 839, in run
    rc = test_mod.run(
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_nfs/nfs_snaphshot_clone.py", line 189, in run
    client1.exec_command(sudo=True, cmd=f"umount {nfs_mounting_dir}")
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 2305, in exec_command
    return self.node.exec_command(cmd=cmd, **kw)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 1700, in exec_command
    raise CommandFailed(
ceph.ceph.CommandFailed: umount /mnt/nfs_Y05CX returned umount: /mnt/nfs_Y05CX: not mounted.
 and code 32 on 10.0.195.251
2025-04-14 13:54:07,371 - cephci - ceph:1576 - INFO - Execute podman --version | awk {'print $3'} on 10.0.195.21
2025-04-14 13:54:08,374 - cephci - ceph:1606 - INFO - Execution of podman --version | awk {'print $3'} on 10.0.195.21 took 1.003358 seconds
2025-04-14 13:54:08,375 - cephci - run:1065 - INFO - Podman Version 5.2.2
2025-04-14 13:54:08,376 - cephci - ceph:1576 - INFO - Execute docker --version | awk {'print $3'} on 10.0.195.21
2025-04-14 13:54:09,381 - cephci - ceph:1606 - INFO - Execution of docker --version | awk {'print $3'} on 10.0.195.21 took 1.003871 seconds
2025-04-14 13:54:09,383 - cephci - ceph:1576 - INFO - Execute ceph --version | awk '{print $3}' on 10.0.195.251
2025-04-14 13:54:10,387 - cephci - ceph:1606 - INFO - Execution of ceph --version | awk '{print $3}' on 10.0.195.251 took 1.003772 seconds
2025-04-14 13:54:10,388 - cephci - run:1081 - INFO - ceph Version 19.2.1-126.el9cp
2025-04-14 13:54:10,389 - cephci - run:1040 - INFO - ceph_clusters_file rerun/regression-vHr823-FUTHJO
2025-04-14 13:54:10,389 - cephci - run:927 - INFO - Test <module 'cephfs_nfs.nfs_snaphshot_clone' from '/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_nfs/nfs_snaphshot_clone.py'> failed
